#pragma once

#include <gst/gst.h>
#include <gst/rtp/gstrtphdrext.h>

typedef struct _GstRTPHeaderExtensionRandomNumberStream {
	GstRTPHeaderExtension parent;

} GstRTPHeaderExtensionRandomNumberStream;

typedef struct _GstRTPHeaderExtensionRandomNumberStreamClass {
	GstRTPHeaderExtensionClass parent_class;
} GstRTPHeaderExtensionRandomNumberStreamClass;

#define RANDOM_NUMBER_STREAM_HDR_EXT_URI "random-number-stream:1.0"

#define GST_TYPE_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM (gst_rtp_header_extension_random_number_stream_get_type())
#define GST_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM, GstRTPHeaderExtensionRandomNumberStream))
#define GST_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM, GstRTPHeaderExtensionRandomNumberStreamClass))
#define GST_IS_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM))
#define GST_IS_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_RTP_HEADER_EXTENSION_RANDOM_NUMBER_STREAM))

GType gst_rtp_header_extension_random_number_stream_get_type(void);
GST_ELEMENT_REGISTER_DECLARE(rtp_header_extension_random_number_stream)